apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployments.secrets.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pdbs.mambuaccountservice.labels" . | indent 4 }}
type: Opaque
data:
  {{ range .Values.deployments.secrets.data }}
  {{ .name }} : "{{ .value }}"
  {{ end }}
